/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dms.auctionspider.bak

import dms.auctionhouse.spider.taobao.TaobaoAddressSpider
import dms.auctionspider.bak.bean.FinalBean
import org.openqa.selenium.chrome.ChromeDriver
import org.openqa.selenium.chrome.ChromeOptions
import java.io.File
import java.text.DateFormat
import java.util.*
import java.util.concurrent.TimeUnit
import kotlin.collections.ArrayList


class App {
    companion object{
        val beanarray=ArrayList<FinalBean>()
    }

    lateinit var driver:ChromeDriver;
    fun run() {

        initProperities()
        println("Loaded Propertities")
        initFile()
        println("Loaded Files")
        try {
            runSpiders()
        }catch(e: Exception){
            println("Error happened while spidering")
        }finally{
            driver.close();
            driver.quit();
        }
            println("Program finished ")
    }
    private fun initProperities() {
        val chromeOptions = ChromeOptions()
//          设置为 headless 模式 （必须） //          设置为 headless 模式 （必须）
   //      chromeOptions.addArguments("--headless")
        driver= ChromeDriver(chromeOptions)
        driver.manage().timeouts().implicitlyWait(8, TimeUnit.SECONDS);
        driver.manage().timeouts().setScriptTimeout(8, TimeUnit.SECONDS)
        driver.manage().timeouts().pageLoadTimeout(8, TimeUnit.SECONDS)

    }

    private fun runSpiders() {
        println("Starting launching spiders")
        TaobaoAddressSpider(driver).start()
        println("TaobaoSpider Started")
    }
    private fun initFile(){
        var file= File("./"+ DateFormat.getDateInstance(DateFormat.DEFAULT).format(Date())+".xls");

        if(file.exists())
            file.delete()
        file.createNewFile();

    }
}

fun main(args: Array<String>) {
 App().run()
}
