/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dms.auctionspider

import dms.auctionhouse.spider.taobao.TaobaoAddressSpider
import dms.auctionspider.bean.FinalBean
import dms.auctionspider.storage.ExcelStorage
import org.openqa.selenium.WebDriver
import org.openqa.selenium.chrome.ChromeDriver
import org.openqa.selenium.chrome.ChromeOptions
import java.util.concurrent.TimeUnit


class App {
    companion object{
        val beanarray=ArrayList<FinalBean>()
    }

    lateinit var driver:ChromeDriver;
    fun run() {

        initProperities()
        println("Loaded Propertities")
        runSpiders()
        println("Program finished ")
    }
    private fun initProperities() {
        val chromeOptions = ChromeOptions()
//          设置为 headless 模式 （必须） //          设置为 headless 模式 （必须）
         chromeOptions.addArguments("--headless")
        driver= ChromeDriver(chromeOptions)
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        driver.manage().timeouts().setScriptTimeout(3, TimeUnit.SECONDS)
        driver.manage().timeouts().pageLoadTimeout(3, TimeUnit.SECONDS)

    }

    private fun runSpiders() {
        println("Starting launching spiders")
        TaobaoAddressSpider(driver).start()
        println("TaobaoSpider Started")
    }
}

fun main(args: Array<String>) {
 App().run()
}
